port: 8081
database:
  host: "localhost"
  port: 27017
  user: "root"
  password: "3Ain2909yVMd2eVImO5luukC"
  db_name: "weather"
  min_pool: 1
  max_pool: 10
message_queue:
  rabbitmq_uri: "amqp://rabbitmq:rabbitmq@localhost:5672/"
  exchange_name: "onboard"
  routing_key: "test"
  queue: "location_data"

weather_apikey: "a2a5f750fbca4b04bd5121342230707"
weather_api_baseurl: "https://api.open-meteo.com/v1/forecast"