// Code generated by mockery v2.26.1. DO NOT EDIT.

package repository

import mock "github.com/stretchr/testify/mock"

// MockMessageQueue is an autogenerated mock type for the MessageQueue type
type MockMessageQueue struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *MockMessageQueue) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Publish provides a mock function with given fields: message
func (_m *MockMessageQueue) Publish(message *User) error {
	ret := _m.Called(message)

	var r0 error
	if rf, ok := ret.Get(0).(func(*User) error); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockMessageQueue interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockMessageQueue creates a new instance of MockMessageQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockMessageQueue(t mockConstructorTestingTNewMockMessageQueue) *MockMessageQueue {
	mock := &MockMessageQueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
